blank_issues_enabled: false
contact_links:
  - name: ğŸš€ Feature request
    url: https://forum.snigdhaos.org/t/feature-request
    about: Updating the description. 
  - name: â“ Simple question - Forum Support
    url: https://forum.snigdhaos.org/t/support
    about: This issue tracker is not for technical support. Please ask the community for help.
  - name: â“ Simple question - Stack Overflow
    url: https://stackoverflow.com/questions/tagged/snigdhaos
    about: This issue tracker is not for technical support. Please use Stack Overflow, and ask the community for help.
  